# Generated by Django 4.2.3 on 2023-07-24 04:20

from django.db import migrations, models
import explorer.validators.urls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=200, validators=[explorer.validators.urls.validate_ws_url])),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
