# Generated by Django 4.2.3 on 2023-07-30 18:20

from django.db import migrations, models
import explorer.validators.urls
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=200, unique=True, validators=[explorer.validators.urls.validate_ws_url])),
                ('full_metadata', models.JSONField(blank=True, null=True)),
                ('pubkey', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.EmailField(blank=True, max_length=255, null=True)),
                ('software', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_required', models.BooleanField(default=False)),
                ('payments_url', models.URLField(blank=True, max_length=1048, null=True)),
                ('admission_fees_sats', models.IntegerField(blank=True, null=True)),
                ('publication_fees_sats', models.IntegerField(blank=True, null=True)),
                ('limitations', models.JSONField(blank=True, null=True)),
                ('tracked_since', models.DateTimeField(auto_now_add=True)),
                ('last_metadata_update', models.DateTimeField(blank=True, null=True)),
                ('last_update_success', models.BooleanField(blank=True, null=True)),
                ('active_tracking', models.BooleanField(default=True)),
                ('supported_nips', models.ManyToManyField(blank=True, to='explorer.nip')),
            ],
        ),
    ]
