# Generated by Django 4.2.3 on 2023-07-28 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_rename_metadata_relay_full_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relay',
            name='active_tracking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relay',
            name='tracked_since',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
