# Generated by Django 4.2.3 on 2023-07-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0005_relay_last_metadata_update_relay_last_update_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='NIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='relay',
            name='supported_nips',
        ),
        migrations.AddField(
            model_name='relay',
            name='supported_nips',
            field=models.ManyToManyField(blank=True, to='explorer.nip'),
        ),
    ]
